---
# Playbook for Web Server

- name: Install httpd and php
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql

- name: Install web role specific dependencies
  yum: name={{ item }} state=installed
  with_items:
   - git

- name: Start & Enable Apache Server to start on boot
  service: name=httpd state=started enabled=yes


- include: copy_code.yml